### ISSUE TITLE
[Feature request] Rendering markdown in the cards

### ISSUE THREAD

**Issue by danieltomasz** [hkgnp/logseq-kanban-plugin#1]
Great plugin, thank you for making it!
Do you plan to work to extend the plugin that the wiki-links [[ ]] may be rendered as links, and they will be clickable?
Also, the same with  Markdown `[Description](Link)`, would be great to have a possibility to click on it.

**Comment by almereyda** [comment]
Indeed a very much anticipated feature for Logseq, with an impressively simple interface. With linked titles being on card titles, this allowed for a very quick two-dimensional skimming of Kanbans with browsing the links' hover cards.

**Comment by hkgnp** [comment]
Thanks all for your suggestion! Unfortunately. this implementation uses the MacroRenderer method in the plugin, which does not actually manipulate Logseq's blocks, i.e. it does not actually create blocks in the Kanban board, hence it's not possible to implement things like linking, etc.

Perhaps @cannibalox's Kanban implementation maybe more suitable for your use case as it uses CSS to re-render the blocks in columns (https://github.com/cannibalox/logtools).

Apologies!
