### ISSUE TITLE
discussion: is it necessary to show todo in deeper level?

### ISSUE THREAD

**Issue by happy15** [hkgnp/logseq-kanban-plugin#10]
it's merely a discussion rather than a feature request.

consider structure below which i use daily:

- tasks
   - [ ] later important task
       - [ ] later important sub task

is it necessary to include the "import sub task" todo in the kanban?

**Comment by hkgnp** [comment]
Hmm, I did consider it previously but because the kanban cards only has one level, I didn't implement it!
