### ISSUE TITLE
maybe disable kanban in the reference section of pages

### ISSUE THREAD

**Issue by happy15** [hkgnp/logseq-kanban-plugin#11]
![image](https://user-images.githubusercontent.com/983570/150733654-38b1f14f-27e6-4afb-ba4f-78a679218639.png)

the screenshot above shows the problem.

it's nice to have kanban disabled in the reference section of pages.

again, nice plugin. 👍

**Comment by hkgnp** [comment]
@happy15 Hmm, it looks like your tasks are not nested as a block under the "tasks" block, that's why the kanban is not showing.
