### ISSUE TITLE
The query condition is invalid

### ISSUE THREAD

**Issue by yunxi177** [hkgnp/logseq-kanban-plugin#13]
Thank you for developing such a great plugin，I ran into some problems while using it。
I want to query tasks with due date in this week. but it is not work.
query statements: 
```
#+BEGIN_QUERY
{:title " Scheduled TODOs"
:query [:find (pull ?b [*])
:in $ ?start ?next
:where
[?b :block/marker ?marker]
[?b :block/deadline ?d]
[(> ?d ?start)]
[(< ?d ?next)]
[(contains? #{"NOW" "LATER" "DOING"} ?marker)]]
:inputs [:today :7d-after]
:collapsed? false}
#+END_QUERY
```
where am i doing wrong?

**Comment by hkgnp** [comment]
Hi!
Unfortunately previously, the API version of the datascript query does not support inputs.
However, I think the devs just updated the API.
Will look into allowing inputs for the queries.

**Comment by yunxi177** [comment]
Thank you for your answer, looking forward to adding this feature.

**Comment by hkgnp** [comment]
Hi, this should be working on v2.7.0.
