### ISSUE TITLE
有字体的颜色就好了

### ISSUE THREAD

**Issue by uulaile** [hkgnp/logseq-kanban-plugin#14]
工具非常好，能一目了然的查看写的东西。如果看板上的字体颜色能和下面的Block中字体颜色显示相同，就更好了。

**Comment by hkgnp** [comment]
Sorry I am not sure what you mean?

**Comment by uulaile** [comment]
board's colours.I hope

**Comment by uulaile** [comment]
![image](https://user-images.githubusercontent.com/96331996/161200408-f445c62d-c74f-44c0-ac0a-6b165b9357f6.png)

**Comment by hkgnp** [comment]
Hmm, I am not familiar with changing the colours of the text from within Logseq, without CSS.

Can you share how you are able to do it and I will try to see if I am able to support it?
