### ISSUE TITLE
BUG:修改一个块的看板大小，整个Page的看板宽度都会随着变大变小。

### ISSUE THREAD

**Issue by uulaile** [hkgnp/logseq-kanban-plugin#15]

**Comment by hkgnp** [comment]
Can you provide a screenshot?

**Comment by uulaile** [comment]
![动画](https://user-images.githubusercontent.com/96331996/160541681-0da85d60-0328-43b8-bfa3-b920f89a4a64.gif)

**Comment by uulaile** [comment]
上下两个块会一起变化，不是单独变化的。

**Comment by hkgnp** [comment]
Fixed in v2.7.1.
