### ISSUE TITLE
I have this problem that I input "DOING" under data.

### ISSUE THREAD

**Issue by lejiaxin** [hkgnp/logseq-kanban-plugin#19]
![image](https://user-images.githubusercontent.com/25132373/175194924-453fa5ee-bc57-4147-8b82-83bee6743247.png)

**Comment by hkgnp** [comment]
Is your format markdown or org-mode?

**Comment by zhiqi-wiki** [comment]
hi @hkgnp, 

The CLOCK and DEADLINE are hidden, but the SCHEDULED is still not. Could you please add it also? Should be similar to DEADLINE . thanks.

**Comment by hkgnp** [comment]
Please see v2.7.6.
