### ISSUE TITLE
希望能自定义边框的粗细（包括不可见）。

### ISSUE THREAD

**Issue by BopSun** [hkgnp/logseq-kanban-plugin#21]
我利用看板功能实现图文并排的功能，但目前看板的边框显得过宽，无法自定义调节。

如果可以自定义，我觉得还能实现分类图库的作用。

非常感谢！

**Comment by BopSun** [comment]
I use the Kanban function to realize the function of picture and text side by side, but at present, the border of Kanban is too wide to be self-adjusted.

If it can be customized, I think it can also achieve the function of classified gallery.

Thank you very much！

**Comment by hkgnp** [comment]
Sorry I don't really understand. Could you provide a bigger screenshot please?

**Comment by BopSun** [comment]
![image](https://user-images.githubusercontent.com/29018648/212778267-923a90d7-80cf-41b0-8e41-6b35a3c1950f.png)

The red area is too wide. I hope the kanban spacing can be more compact.

**Comment by hkgnp** [comment]
Please try in the latest version?
