### ISSUE TITLE
New feature: sort the task by priority

### ISSUE THREAD

**Issue by zhiqi-wiki** [hkgnp/logseq-kanban-plugin#23]
Hi Guys,

Could you please add a new feature to sort the task by priority automatically? thank you very much.

**Comment by hkgnp** [comment]
Apologies, what do you mean by sort by priority? Do you have a screenshot of your blocks to share please?

**Comment by zhiqi-wiki** [comment]
> 

![image](https://user-images.githubusercontent.com/71417523/212724325-4483a6af-4dc3-47ff-8437-09f585988457.png)

the request is to sort the list by tag [#A] and [#B]. this priority tag is a default feature of logseq.

**Comment by hkgnp** [comment]
This feature is available in the latest version. Apologies for the delay.

**Comment by bunnyhero** [comment]
Does this still work? My `query-task` board is not sorting by priority.

**Comment by benjypng** [comment]
@bunnyhero Fixed in latest version.
