### ISSUE TITLE
Tasks fetched by query not working

### ISSUE THREAD

**Issue by lukas-mertens** [hkgnp/logseq-kanban-plugin#25]
Hey, currently I am having trouble figuring out why tasks which are pulled via a query are not showing up. Let me help you reproduce it. This is how it looks to me in a demo-graph I created to test it out:

![image](https://user-images.githubusercontent.com/10901304/214538130-957b578b-36d4-4868-9ef8-3538b86aa691.png)

In your GIF there is a button to update the tasks in the kanban board. As that is not visible I thought it might actually not be necessary anymore.

Let me give you the raw markdown of the page:

```md
- {{renderer :kanban_xvfzgivsb}}
	- tasks
		- query-table:: true
		  #+BEGIN_QUERY
		  {
		  	:title [:h3 "Tasks" ]
		  	:query [
		  	  :find (pull ?b [*])
		  	  :where 
		  			[?b :block/marker ?marker]
		  			[(missing? $ ?b :block/scheduled)]
		  			[?b :block/page ?page]
		  			[?page :block/original-name ?name]
		  		]
		  		:breadcrumb-show? false
		  		:result-transform (fn [result]
		  		(sort-by (fn [h] (get h :block/created-at)) result))
		  		:collapsed? false
		  }
		  #+END_QUERY
```
The query is inspired by the one you used in the GIF, even the exact same one didn't work either though.

Here is the markdown for a page with a few of those todos:

```md
- #quick-project Bake cookies
	- TODO Decide for a recipe
	- TODO Buy the ingredients
	- TODO Prepare the cookies
	- TODO Put everything in the oven
	- TODO Gift cookies to friends
## Meeting-Notes
	- TODO Work on Issue ABC #inbox
## Now some clarified stuff
	- TODO Work on Issue XYZ #he #f #u #45m
	- TODO Clean room #le #60m
```

Adding tasks manually works great:
![image](https://user-images.githubusercontent.com/10901304/214539787-512b6107-603e-40a8-b638-aa6b424b7581.png)

My editor config:
![image](https://user-images.githubusercontent.com/10901304/214539956-adf03d66-38fd-4603-89d1-14fbd18033fa.png)

When disabling table-mode it doesn't work either:
![image](https://user-images.githubusercontent.com/10901304/214540056-ff1f25db-241d-4ff1-ae61-40dd70bda495.png)

If I can give you any additional things to reproduce this, I would be happy to do so!

**Comment by hkgnp** [comment]
Hi, please try v2.7.9.

**Comment by lukas-mertens** [comment]
Hey,

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/10901304/214807754-9aaba023-5547-439e-90a4-544b2f057c93.png">

Sadly, it’s still the same situation. I don’t get any errors in the dev console either.

**Comment by Bohreromir** [comment]
Any updates? I can reproduce its not working

**Comment by lukas-mertens** [comment]
Thanks for figuring this out! I think you should probably match for both cases so maybe you could OR the two ways an advanced query is detected and then do a pr? Hopefully @hkgnp can merge it then

**Comment by hkgnp** [comment]
I've made the changes in 2.7.10. Want to see if it works?
