### ISSUE TITLE
If root node contains 2 words, column width will be treated as board width

### ISSUE THREAD

**Issue by greenrd** [hkgnp/logseq-kanban-plugin#28]
A root node like this doesn't work as I expect:

The rest 200

I have to rewrite it to look like this, which looks ugly:

The-rest 200

The code should look for the last 1 or 2 numbers in the line IMO - not the 2nd and 3rd words.

**Comment by hkgnp** [comment]
Should be fixed in [latest version](https://github.com/hkgnp/logseq-kanban-plugin/releases/tag/v3.0.0).
