### ISSUE TITLE
Left align board

### ISSUE THREAD

**Issue by distefam** [hkgnp/logseq-kanban-plugin#3]
Kanban boards take up a lot of horizontal space. However, when I expand my Logseq window horizontally the left margin grows so that the Kanban board is centered. Is there a way to make the Kanban board take up the full width of the window if it is the top selected bullet?

**Comment by hkgnp** [comment]
Hi! I think this is because there is a central CSS setting to determine the width of the main content column. You can try to increase the width by adding this to your custom.css

```
.cp__sidebar-main-content {
    max-width: 1400px !important;
}
```
