### ISSUE TITLE
Add hyperlinks to cards

### ISSUE THREAD

**Issue by lukekh** [hkgnp/logseq-kanban-plugin#32]
It would be neat if hyperlinks could be added to the cards.

It would be doubly neat if there was an ability to add a subitem which rendered as a markdown description.

Currently this is how it looks:
![image](https://github.com/hkgnp/logseq-kanban-plugin/assets/36324565/6608d42f-8a9f-4880-96ce-4773ae8c86a8)

**Comment by hkgnp** [comment]
This is available in the [latest version](https://github.com/hkgnp/logseq-kanban-plugin/releases/tag/v3.3.0).
