### ISSUE TITLE
Work with Queries for non-tasks

### ISSUE THREAD

**Issue by jonasdiemer** [hkgnp/logseq-kanban-plugin#33]
Hello,

would it be possible to use queries that yield "regular" blocks, not Tasks?

E.g.

```
- {{renderer(:kanban_yeedgiip)}}
	- data
		- New
			- {{query([[New]])}}
		- Active
			- {{query([[Active]])}}
		- Closed
			- {{query([[closed]])}}
```

**Comment by hkgnp** [comment]
Hi, this is available in the latest version. See: https://github.com/hkgnp/logseq-kanban-plugin#normal-with-queries.
