### ISSUE TITLE
Board invisible until config deleted

### ISSUE THREAD

**Issue by stan-voo** [hkgnp/logseq-kanban-plugin#34]
I suppose that's a bug. Whenever I edit board settings, the board disappears. 
I have to delete config to get it back. Here's how it looks: 
![Screen Recording 2023-09-22 at 05 59 26 PM](https://github.com/hkgnp/logseq-kanban-plugin/assets/9213607/03fc1533-e97c-4132-8e73-409d62b721c4)

**Comment by hkgnp** [comment]
You have left your comment on the wrong Github repository.
