### ISSUE TITLE
Is it possible to be used with query?

### ISSUE THREAD

**Issue by Healer137** [hkgnp/logseq-kanban-plugin#6]
https://i.imgur.com/j4rAIxF.png

**Comment by hkgnp** [comment]
Currently not yet, but let me look into it.

**Comment by hkgnp** [comment]
Just a question. Queries typically retrieve multiple results. How would you use them on a Kanban board?

**Comment by lachlancresswell** [comment]
> Just a question. Queries typically retrieve multiple results. How would you use them on a Kanban board?

An example would be:
```
- {{renderer(:kanban_dpjdipddbc)}}
	- data
	    - TODOs
		- {{query((todo todo) )}}
```

Lists all TODO blocks across the entire database as separate cards under the TODO Column.

**Comment by hkgnp** [comment]
Delivered in [v2.6.0](https://github.com/hkgnp/logseq-kanban-plugin#using-queries).
